plugins:
  homepage_redirect:
    enabled:
      default: true
      client: true
      type: bool

    destination_path:
      default: "/discourse-ai/ai-bot/conversations"
      client: true
      type: text
